### ISSUE TITLE
a bug of Pindel : -p  does not exist 

### ISSUE THREAD

**Issue by WinterLi1993** [genome/pindel#22] opened 2015-10-15 02:43 UTC
Hello,
     when I  run "../pindel2vcf -r hs_ref_chr20.fa -R HUMAN_G1K_V2 -d 20100101 -P  colontumor_E  -e  5" on demo folder ,I met this bug:"The pindel file (-p) does not exist".

so what happened  ?
Pindel version 0.2.5b6, 20150915.

**Comment by WinterLi1993** [comment] 2015-10-15 02:43
@liangkaiye

**Comment by liangkaiye** [comment] 2015-10-15 03:23
-p shall be lower case.

**Comment by WinterLi1993** [comment] 2015-10-15 03:35
I have tried lower case and upper case...both aslo show me the same error .....

**Comment by WinterLi1993** [comment] 2015-10-15 03:59
I just run  demo command from this software....

**Comment by liangkaiye** [comment] 2015-10-15 12:07
../pindel2vcf -r hs_ref_chr20.fa -R HUMAN_G1K_V2 -d 20100101 -p colontumor_E -v colontumor_E.vcf

Try this one. You need to specify output file name. No -E

**Comment by WinterLi1993** [comment] 2015-10-15 13:59
Hi ,I just follow Pindel instructions ,,, I feel something wrong in this script.
Can you tell me how to use your software to call somatic Indels ? I have not find any details or pipiline to tell how write command step by step to get somatic indels . Can you give me some detail informations ?

**Comment by EWLameijer** [comment] 2015-10-15 21:03
Kai, Winter,

In the first mail, Winter was talking about pindel2vcf, not Pindel itself.

And for pindel2vcf, -p and -P have different meanings.

-p (lowercase p) is for an individual file, like colo_test_D. The uppercase -P can take a whole bunch of files; using "-P colo_test" processes the files colo_test_D, colo_test_SI, colo_test_TD etc.

That being said, "the pindel file (-p) does not exist" will just mean that either the name of the pindel file is spelled incorrectly or that the file is not in your current directory/the path is wrong.

But overall, I'd recommend you follow the instructions on the website http://gmt.genome.wustl.edu/packages/pindel/quick-start.html

First install Pindel (there may be some prompts for dependencies)

./INSTALL

Then (stay in the main directory) run 

./pindel -f demo/hs_ref_chr20.fa -p demo/COLO-829_20-p_ok.txt -c 20 -o output/ref

Finally, run Pindel2vcf:

./pindel2vcf -r demo/hs_ref_chr20.fa -R HUMAN_G1K_V2 -d 20100101 -P output/ref

You will see a ref.vcf appear in the output folder.

In general, while we try to make Pindel as easy to use as possible and try to reply as fast as possible to questions, you may want to consult with one of the (other) local bioinformaticians or scientific programmers if Pindel does not seem to work; they may see much faster what the problem is than we can from here.

On calling somatic indels... Pindel, by itself, just calls indels relative to the reference genome. You need at least two samples (and certain scripts) to find somatic indels; perhaps Kai can help here (or we can put some things on the website - I'm quite sure there are some scripts around, but Kai probably has those more readily available than I do)

Best regards,

Eric-Wubbo

**Comment by liangkaiye** [comment] 2015-10-15 22:00
there is one somatic filtering script in Pindel package. We just added 
it recently and will provide documentation shortly.

**Comment by WinterLi1993** [comment] 2015-10-16 02:15
@EWLameijer ,
 Thank you very much!

yep, I prepare two samples (tumor-normal sample).And I call somatic Indels  with these commands:

#Step 1： Prepare normal_tumor.config.txt  
simulated_sample_1.bam	250	normal
simulated_sample_2.bam	250	tumor  

#Step 2：Call somatic Indels (  turn on "N" )
../pindel  -i normal_tumor.config.txt  -f simulated_reference.fa -o li -c All -r false -N true -L li.log -l false -t false 

I  got these results : 
       0 10月 16 09:23 li_TD
       0 10月 16 09:23 li_INV
       0 10月 16 09:23 li_LI
        0 10月 16 09:23 li_BP
       0 10月 16 09:23 li_CloseEndMapped
   12371 10月 16 09:24 li_RP
   106403 10月 16 09:24 li_D
   85719 10月 16 09:24 li_SI
       0 10月 16 09:24 li_INT_final
    7750 10月 16 09:24 li.log

So I have these questions:
1. RP means what  ?
2. My steps to call somatic Indels  are right ?

**Comment by EWLameijer** [comment] 2015-10-26 22:10
1) Hmm... Kai can answer this better than I can, but to my understanding RP means 'read pair', Kai could be more explicit about its use, though... Note, though that, insertions/deletions/tandem duplications and insertions are the data you would be more interested in anyway, so I think it is okay to ignore 'RP' for the moment, especially given your second question.

2) Your steps to call somatic indels don't seem exactly right to me, you need a separate script to process the pindel output (or pindel2vcf output), basically to look for those indels that are in the tumor sample (with a certain coverage) but not in the reference sample. You can ask Kai (I'm sure he has a script somewhere), or write it yourself or ask your local bioinformatician to write it for you (I'm currently in Cannes and far away from my home computer, so writing and testing a script would be hard for me at the moment).

Other remarks: 
a) usually insert size is much larger than 250, usually you should find some information about insert size with the person who made your library. If you really don't know, then 500 or 600 would be a better gamble, especially if your reads are 100-105 bp long.
b) as the reference genome for pindel, always use the genome that was also used for creating the bam-file; 'simulated_reference.fa' does not seem like a proper reference (unless, of course, you are running a test on a simulated tumor sample,...)

**Comment by EWLameijer** [comment] 2016-08-17 13:55
Closing this issue as half a year has gone by without further questions.

**Closed by EWLameijer** 2016-08-17 13:55 UTC
